# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

admin_api_aisel_backenduser_get_collection:
    pattern:   /backenduser/
    defaults:  { _controller: AiselBackendUserBundle:Admin/Api:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_aisel_backenduser_get:
    pattern:   /backenduser/{id}
    defaults:  { _controller: AiselBackendUserBundle:Admin/Api:get, _format: json }
    requirements:
        _method: GET

admin_api_aisel_backenduser_put:
    pattern:   /backenduser/{id}
    defaults:  { _controller: AiselBackendUserBundle:Admin/Api:put, _format: json }
    requirements:
        _method: PUT

admin_api_aisel_backenduser_delete:
    pattern:   /backenduser/{id}
    defaults:  { _controller: AiselBackendUserBundle:Admin/Api:delete, _format: json }
    requirements:
        _method: DELETE

admin_api_aisel_backenduser_post:
    pattern:   /backenduser/
    defaults:  { _controller: AiselBackendUserBundle:Admin/Api:post, _format: json }
    requirements:
        _method: POST

admin_api_aisel_backenduser_login:
    pattern:  /user/login/
    defaults: { _controller: AiselBackendUserBundle:Api:login, _format: json }
    requirements:
        _method: POST

admin_api_aisel_backenduser_logout:
    pattern:  /user/logout/
    defaults: { _controller: AiselBackendUserBundle:Api:logout, _format: json }
    requirements:
        _method: GET

admin_api_aisel_backenduser_information:
    pattern:  /user/information/
    defaults: { _controller: AiselBackendUserBundle:Api:information, _format: json }
    requirements:
        _method: GET
