parameters:
    application.name: Aisel
    application.version: 0.3.0
    application.media.path: /media
    application.media.product.path: /media/product
    application.media.product.main.path: /media/product
    application.media.product.upload_dir: %kernel.root_dir%/../web%application.media.product.main.path%
    application.media.product.upload_path: %application.media.product.main.path%
    website_admin: administration
    frontend_api: api
    backend_api: backend/api

aisel_config:
    entities:
        content:
            order: 100
            fields:
                homepage:
                    type: textarea
                footer:
                    type: input

        meta:
            order: 200
            fields:
                title:
                    type: input
                description:
                    type: input
                keywords:
                    type: input
        contact:
            order: 300
            fields:
              name:
                type: input
              email:
                type: input
              phone:
                type: input
              message:
                type: textarea

        disqus:
            order: 500
            fields:
              key:
                type: input

aisel_fixture:
    xml_path: /fixtures/xml

aisel_order:
    payment_methods:
        offline:
            title: "Offline Payment"
        paypal_express_checkout_nvp:
            title: "Paypal Express Checkout"
