# Doctrine Configuration
stof_doctrine_extensions:
    default_locale: en_US
    mongodb:
        default:
            timestampable: true

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: aisel
    document_managers:
        default:
            auto_mapping: true