# Doctrine Configuration
stof_doctrine_extensions:
    default_locale: en_US
    mongodb:
        default:
            tree: true
            timestampable: true

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: aisel
    document_managers:
        default:
            auto_mapping: true
            mappings:
                gedmo_tree:
                    type: annotation
                    prefix: Gedmo\Tree\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Document"
                    alias: GedmoTree # this one is optional and will default to the name set for the mapping
                    is_bundle: false