# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

#CRUD
admin_api_aisel_user_get_collection:
    pattern:   /user/
    defaults:  { _controller: AiselUserBundle:Admin/Api:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_get:
    pattern:   /user/{id}
    defaults:  { _controller: AiselUserBundle:Admin/Api:get, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_put:
    pattern:   /user/{id}
    defaults:  { _controller: AiselUserBundle:Admin/Api:put, _format: json }
    requirements:
        _method: PUT

admin_api_aisel_user_delete:
    pattern:   /user/{id}
    defaults:  { _controller: AiselUserBundle:Admin/Api:delete, _format: json }
    requirements:
        _method: DELETE

admin_api_aisel_user_post:
    pattern:   /user/
    defaults:  { _controller: AiselUserBundle:Admin/Api:post, _format: json }
    requirements:
        _method: POST


# Login
admin_api_aisel_user_login:
    pattern:  /user/login/
    defaults: { _controller: AiselUserBundle:Api:login, _format: json }
    requirements:
        _method: POST

admin_api_aisel_user_logout:
    pattern:  /user/logout/
    defaults: { _controller: AiselUserBundle:Api:logout, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_information:
    pattern:  /user/information/
    defaults: { _controller: AiselUserBundle:Api:information, _format: json }
    requirements:
        _method: GET