# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

#admin_login:
#    pattern:   /%website_admin%/%locale%/login
#    defaults:  { _controller: AiselBackendUserBundle:Login:login }
#    requirements:
#        _method: GET
#
#admin_login_check:
#    pattern:   /%website_admin%/%locale%/login_check
#
#admin_logout:
#    pattern:   /%website_admin%/%locale%/logout

# Backend
admin_api_aisel_backenduser_get_collection:
    pattern:   /%backend_api%/backenduser/
    defaults:  { _controller: AiselBackendUserBundle:Admin/Api:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_aisel_backenduser_get:
    pattern:   /%backend_api%/backenduser/{id}
    defaults:  { _controller: AiselBackendUserBundle:Admin/Api:get, _format: json }
    requirements:
        _method: GET

# Fontend
admin_api_aisel_user_login:
    pattern:  /%backend_api%/user/login.json
    defaults: { _controller: AiselBackendUserBundle:Api:login, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_logout:
    pattern:  /%backend_api%/user/logout.json
    defaults: { _controller: AiselBackendUserBundle:Api:logout, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_information:
    pattern:  /%backend_api%/user/information.json
    defaults: { _controller: AiselBackendUserBundle:Api:information, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_editdetails:
    pattern:  /%backend_api%/user/editdetails.json
    defaults: { _controller: AiselBackendUserBundle:Api:editdetails, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_register:
    pattern:  /%backend_api%/user/register.json
    defaults: { _controller: AiselBackendUserBundle:Api:register, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_passwordforgot:
    pattern:  /%backend_api%/user/passwordforgot.json
    defaults: { _controller: AiselBackendUserBundle:Api:passwordforgot, _format: json }
    requirements:
        _method: GET
