# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    aisel.user.backend:
        class: Aisel\BackendUserBundle\Admin\BackendUserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Backend" }
        arguments:
            - ~
            - Aisel\BackendUserBundle\Entity\BackendUser
            - ~
        calls:
            - [ setTranslationDomain, [forms]]
            - [ setEncoderFactory, [ @security.encoder_factory ] ]


    backend.user.manager:
        class: Aisel\BackendUserBundle\Manager\UserManager
        arguments: [@doctrine.orm.entity_manager, @security.encoder_factory, @security.context]
