# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    backend.user.manager:
        class: Aisel\BackendUserBundle\Manager\UserManager
        arguments:
          - @doctrine.odm.mongodb.document_manager
          - @security.encoder_factory
          - @security.context

    aisel_backend_user_persistence_listener:
        class: Aisel\BackendUserBundle\EventListener\UserPersistenceListener
        arguments:
            - @security.encoder_factory
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
