# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_order_collection:
    pattern:  /orders/my
    defaults: { _controller: AiselOrderBundle:ApiOrder:orderList, _format: json }
    requirements:
        _method: GET

api_aisel_order_get:
    pattern:  /order/{id}
    defaults: { _controller: AiselOrderBundle:ApiOrder:orderViewById, _format: json }
    requirements:
        _method: GET

api_aisel_order_post:
    pattern:  /{locale}/order
    defaults: { _controller: AiselOrderBundle:ApiOrder:orderSubmit, _format: json }
    requirements:
        _method: POST

api_aisel_order_checkout:
    pattern:  /{locale}/order/checkout
    defaults: { _controller: AiselOrderBundle:ApiCheckout:init, _format: json }
    requirements:
        _method: GET
