# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Frontend
api_aisel_pagelist:
    pattern:  /%frontend_api%/{locale}/page/
    defaults: { _controller: AiselPageBundle:Page:pageList, _format: json }
    requirements:
        _method: GET

api_aisel_pageview_by_url:
    pattern:  /%frontend_api%/{locale}/page/{urlKey}
    defaults: { _controller: AiselPageBundle:Page:pageViewByURL, _format: json }
    requirements:
        _method: GET

api_aisel_page_categorylist:
    pattern:  /%frontend_api%/{locale}/page/category/
    defaults: { _controller: AiselPageBundle:Node:categoryList, _format: json }
    requirements:
        _method: GET

api_aisel_page_categorytree:
    pattern:  /%frontend_api%/{locale}/page/category/tree/
    defaults: { _controller: AiselPageBundle:Node:categoryTree, _format: json }
    requirements:
        _method: GET

api_aisel_page_categoryview:
    pattern:  /%frontend_api%/{locale}/page/category/view/{urlKey}
    defaults: { _controller: AiselPageBundle:Node:categoryView, _format: json }
    requirements:
        _method: GET
        id: "\d+"
