# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_page_get:
    pattern:  /{locale}/page/
    defaults: { _controller: AiselPageBundle:ApiPage:getCollection, _format: json }
    requirements:
        _method: GET

api_aisel_page_get_by_url:
    pattern:  /{locale}/page/{url}
    defaults: { _controller: AiselPageBundle:ApiPage:getByURL, _format: json }
    requirements:
        _method: GET

api_aisel_page_category_get:
    pattern:  /{locale}/page/category/
    defaults: { _controller: AiselPageBundle:ApiNode:getCollection, _format: json }

    requirements:
        _method: GET

api_aisel_page_category_get_by_url:
    pattern:  /{locale}/page/category/view/{url}
    defaults: { _controller: AiselPageBundle:ApiNode:getByURL, _format: json }
    requirements:
        _method: GET
        id: "\d+"

api_aisel_page_category_get_tree:
    pattern:  /{locale}/page/category/tree/
    defaults: { _controller: AiselPageBundle:ApiNode:getTree, _format: json }
    requirements:
        _method: GET
