# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_pagelist:
    pattern:  /{locale}/page/
    defaults: { _controller: AiselPageBundle:ApiPage:pageList, _format: json }
    requirements:
        _method: GET

api_aisel_pageview_by_url:
    pattern:  /{locale}/page/{urlKey}
    defaults: { _controller: AiselPageBundle:ApiPage:pageViewByURL, _format: json }
    requirements:
        _method: GET

api_aisel_page_categorylist:
    pattern:  /{locale}/page/category/
    defaults: { _controller: AiselPageBundle:ApiNode:categoryList, _format: json }
    requirements:
        _method: GET

api_aisel_page_categorytree:
    pattern:  /{locale}/page/category/tree/
    defaults: { _controller: AiselPageBundle:ApiNode:categoryTree, _format: json }
    requirements:
        _method: GET

api_aisel_page_categoryview:
    pattern:  /{locale}/page/category/view/{urlKey}
    defaults: { _controller: AiselPageBundle:ApiNode:categoryView, _format: json }
    requirements:
        _method: GET
        id: "\d+"
