# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

admin_api_aisel_user_login:
    pattern:  /user/login.json
    defaults: { _controller: AiselBackendUserBundle:Api:login, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_logout:
    pattern:  /user/logout.json
    defaults: { _controller: AiselBackendUserBundle:Api:logout, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_information:
    pattern:  /user/information.json
    defaults: { _controller: AiselBackendUserBundle:Api:information, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_editdetails:
    pattern:  /user/editdetails.json
    defaults: { _controller: AiselBackendUserBundle:Api:editdetails, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_register:
    pattern:  /user/register.json
    defaults: { _controller: AiselBackendUserBundle:Api:register, _format: json }
    requirements:
        _method: GET

admin_api_aisel_user_passwordforgot:
    pattern:  /user/passwordforgot.json
    defaults: { _controller: AiselBackendUserBundle:Api:passwordforgot, _format: json }
    requirements:
        _method: GET
