# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

admin_api_aisel_product_get:
    pattern:   /product/{id}
    defaults:  { _controller: AiselProductBundle:Admin/Product:get, _format: json }
    requirements:
        _method: GET

admin_api_aisel_product:
    pattern:   /product/
    defaults:  { _controller: AiselProductBundle:Admin/Product:post, _format: json }
    requirements:
        _method: POST
