# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_product_get_collection:
    pattern:  /{locale}/product/
    defaults: { _controller: AiselProductBundle:ApiProduct:getCollection, _format: json }
    requirements:
        _method: GET

api_aisel_product_get_by_url:
    pattern:  /{locale}/product/{url}
    defaults: { _controller: AiselProductBundle:ApiProduct:getByURL, _format: json }
    requirements:
        _method: GET

api_aisel_product_category_get_by_url:
    pattern:  /{locale}/product/category/{url}
    defaults: { _controller: AiselProductBundle:ApiNode:getByURL, _format: json }
    requirements:
        _method: GET
        id: "\d+"

api_aisel_product_category_get:
    pattern:  /{locale}/product/category/
    defaults: { _controller: AiselProductBundle:ApiNode:getNodeCollection, _format: json }
    requirements:
        _method: GET

api_aisel_product_category_get_tree:
    pattern:  /{locale}/product/category/tree/
    defaults: { _controller: AiselProductBundle:ApiNode:getTreeEnabled, _format: json }
    requirements:
        _method: GET
