language: php

php:
    - 5.4

branches:
    only:
        - master

before_install:
    # Install node.js
    - npm install -g grunt-cli

install:

    # Install php packages
    - sudo apt-get update > /dev/null
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl

    # Create VirtualHost
    - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
    - sudo sed -i -e "/DocumentRoot/i\ServerName aisel.dev" /etc/apache2/sites-available/default
    - echo "127.0.0.1 aisel.dev" | sudo tee -a /etc/hosts
    - sudo /etc/init.d/apache2 restart

    # Install node packages
    - npm install
    - node -v


before_script:
    # Update composer
    - composer self-update
    - composer install

    # Copy skeleton parameters file & Load Fixtures
    - cp app/config/parameters.yml.travis app/config/parameters.yml
    - php app/console doctrine:database:create --env=test > /dev/null
    - php app/console doctrine:schema:create --env=test > /dev/null
    - php app/console doctrine:fixtures:load --env=test > /dev/null
    - php app/console assets:install web --symlink
    - php app/console cache:warmup --env=test > /dev/null
    - chmod -R 777 app/cache app/logs
    - chmod -R 777 app/cache app/logs

script:
    - grunt karma:unit