projectx_admin_homepage:
    pattern:  /admin/custompage
    defaults: { _controller: ProjectxAdminBundle:Default:index }

#sonata_admin_custompage:
#    pattern:  /admin/custompage
#    defaults: { _controller: AcmeDemoBundle:Admin:custompage }