parameters:
#    projectx_admin.example.class: Projectx\AdminBundle\Example

services:
#    projectx_admin.example:
#        class: %projectx_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
