# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\NavigationBundle\Entity\Menu:
#  exclusion_policy: ALL
  properties:
#    id:
#        expose: true
#    title:
#        expose: true
#    metaUrl:
#        expose: true
#    description:
#        expose: true
