# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\OrderBundle\Entity\OrderItem:
    type: entity
    table: aisel_order_item
    repositoryClass: Aisel\OrderBundle\Entity\OrderItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 255
        price:
            type: integer
            default: 0
        qty:
            type: integer
            default: 0
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    manyToOne:
      order:
        targetEntity: Aisel\OrderBundle\Entity\Order
        inversedBy: orderItem
        joinColumn:
          name: order_id
          referencedColumnName: id

      product:
        targetEntity: Aisel\ProductBundle\Entity\Product
        inversedBy: orderItem
        joinColumn:
          name: product_id
          referencedColumnName: id