# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\OrderBundle\Entity\Order:
    type: entity
    table: aisel_order
    repositoryClass: Aisel\OrderBundle\Entity\OrderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 2
            nullable: false

        status:
            type: string
            length: 255
        subtotal:
            type: integer
            default: 0
            nullable: true
        grandtotal:
            type: integer
            default: 0
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    oneToOne:
      frontenduser:
        targetEntity: Aisel\FrontendUserBundle\Entity\FrontendUser
        joinColumn:
          name: user_id
          referencedColumnName: id

      invoice:
        targetEntity: Aisel\OrderBundle\Entity\Invoice
        joinColumn:
          name: invoice_id
          referencedColumnName: id


    oneToMany:
      item:
        targetEntity: Aisel\OrderBundle\Entity\OrderItem
        mappedBy: order