parameters:
    application.name: Aisel
    application.version: 0.0.3

aisel_config:
    route_prefix: config_ # ex: config_contact
    entities:
        homepage:
            order: 0
            controller: AiselAdminBundle:ConfigHomepage:modify
        meta:
            order: 10
            controller: AiselAdminBundle:ConfigMeta:modify
        contact:
            order: 20
            controller: AiselContactBundle:Config:modify
        disqus:
            order: 30
            controller: AiselAdminBundle:ConfigDisqus:modify

# for later use
#        category:
#            order: 30
#            controller: AiselCategoryBundle:Config:modify
