aisel_contact:
    resource: "@AiselContactBundle/Resources/config/routing.yml"
    prefix:   /

aisel_category:
    resource: "@AiselCategoryBundle/Resources/config/routing.yml"
    prefix:   /

aisel_navigation:
    resource: "@AiselNavigationBundle/Resources/config/routing.yml"
    prefix:   /

aisel_page:
    resource: "@AiselPageBundle/Resources/config/routing.yml"
    prefix:   /

aisel_admin:
    resource: "@AiselAdminBundle/Resources/config/routing.yml"
    prefix:   /

aisel_user_frontend:
    resource: "@AiselFrontendUserBundle/Resources/config/routing.yml"
    prefix:   /

aisel_user_backend:
    resource: "@AiselBackendUserBundle/Resources/config/routing.yml"
    prefix:   /



admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /administration

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /administration

aisel_config:
    resource: .
    type: extra
    prefix: /administration/settings/
