aisel_category:
    resource: "@AiselCategoryBundle/Resources/config/routing.yml"
    prefix:   /

aisel_navigation:
    resource: "@AiselNavigationBundle/Resources/config/routing.yml"
    prefix:   /

aisel_page:
    resource: "@AiselPageBundle/Resources/config/routing.yml"
    prefix:   /

aisel_admin:
    resource: "@AiselAdminBundle/Resources/config/routing.yml"
    prefix:   /

aisel_user:
    resource: "@AiselUserBundle/Resources/config/routing.yml"
    prefix:   /

# SonataUser routing
#sonata_user_security:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
#
#sonata_user_resetting:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
#    prefix: /resetting
#
#sonata_user_profile:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
#    prefix: /profile
#
#sonata_user_register:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
#    prefix: /register
#
#sonata_user_change_password:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
#    prefix: /profile

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /administration

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /administration

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /administration
