aisel_contact:
    resource: "@AiselContactBundle/Resources/config/routing.yml"
    prefix:   /

aisel_navigation:
    resource: "@AiselNavigationBundle/Resources/config/routing.yml"
    prefix:   /

aisel_page:
    resource: "@AiselPageBundle/Resources/config/routing.yml"
    prefix:   /

aisel_search:
    resource: "@AiselSearchBundle/Resources/config/routing.yml"
    prefix:   /

aisel_product:
    resource: "@AiselProductBundle/Resources/config/routing.yml"
    prefix:   /

aisel_cart:
    resource: "@AiselCartBundle/Resources/config/routing.yml"
    prefix:   /

aisel_order:
    resource: "@AiselOrderBundle/Resources/config/routing.yml"
    prefix:   /

aisel_addressing:
    resource: "@AiselAddressingBundle/Resources/config/routing.yml"
    prefix:   /

aisel_user_frontend:
    resource: "@AiselFrontendUserBundle/Resources/config/routing.yml"
    prefix:   /

aisel_user_backend:
    resource: "@AiselBackendUserBundle/Resources/config/routing.yml"
    prefix:   /

aisel_admin:
    resource: "@AiselAdminBundle/Resources/config/routing.yml"
    prefix:   /

aisel_config:
    resource: "@AiselConfigBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/%website_admin%
    requirements:
      _locale: %locales%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/%website_admin%
    requirements:
      _locale: %locales%
