security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

#    acl:
#        connection: default

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#        PAGES:
#            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
#        ROLE_SONATA_USER_STAFF:
#            - ROLE_SONATA_USER_ADMIN_EDIT
#            - ROLE_SONATA_USER_ADMIN_LIST
#            - ROLE_SONATA_USER_ADMIN_CREATE
        # using the staff role to create new roles
#        ROLE_MANAGE_USERS:             [ROLE_SONATA_USER_STAFF]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /administration(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /administration/login
                use_forward:    false
                check_path:     /administration/login_check
                failure_path:   null
                default_target_path: /administration/dashboard
            logout:
                path:           /administration/logout
            anonymous:          true

        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                default_target_path: /
                failure_path:   null
            logout:             true
            anonymous:          true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/administration/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/administration/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }