# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Images
admin_api_aisel_media_image_upload:
    pattern:   /media/image/upload/
    defaults:  { _controller: AiselMediaBundle:Upload:upload, _format: json }

admin_api_aisel_media_image_post:
    pattern:   /media/image/
    defaults:  { _controller: AiselMediaBundle:Admin/ApiImage:post, _format: json }
    requirements:
        _method: POST

admin_api_aisel_media_image_get:
    pattern:   /media/image/{id}
    defaults:  { _controller: AiselMediaBundle:Admin/ApiImage:get, _format: json }
    requirements:
        _method: GET

admin_api_aisel_media_image_put:
    pattern:   /media/image/{id}
    defaults:  { _controller: AiselMediaBundle:Admin/ApiImage:put, _format: json }
    requirements:
        _method: PUT

admin_api_aisel_media_image_delete:
    pattern:   /media/image/{id}
    defaults:  { _controller: AiselMediaBundle:Admin/ApiImage:delete, _format: json }
    requirements:
        _method: DELETE
