# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\ConfigBundle\Entity\Config:
    type: entity
    table: aisel_config
    repositoryClass: Aisel\ConfigBundle\Entity\ConfigRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 2
        entity:
            type: string
            length: 255
        value:
            type: text
