# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Backend
admin_api_aisel_order_get_collection:
    pattern:   /%backend_api%/order/
    defaults:  { _controller: AiselOrderBundle:Admin/Api:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_aisel_order_get:
    pattern:   /%backend_api%/order/{id}
    defaults:  { _controller: AiselOrderBundle:Admin/Api:get, _format: json }
    requirements:
        _method: GET

# Frontend
api_aisel_orderlist:
    pattern:  /%frontend_api%/orders.json
    defaults: { _controller: AiselOrderBundle:ApiOrder:orderList, _format: json }
    requirements:
        _method: GET

api_aisel_orderview_by_id:
    pattern:  /%frontend_api%/order/view/{id}.json
    defaults: { _controller: AiselOrderBundle:ApiOrder:orderViewById, _format: json }
    requirements:
        _method: GET

api_aisel_ordersubmit:
    pattern:  /%frontend_api%/{locale}/order/submit.json
    defaults: { _controller: AiselOrderBundle:ApiOrder:orderSubmit, _format: json }
    requirements:
        _method: POST

api_aisel_ordercheckout_init:
    pattern:  /%frontend_api%/{locale}/order/checkout/init.json
    defaults: { _controller: AiselOrderBundle:ApiCheckout:init, _format: json }
    requirements:
        _method: GET

aisel_payum_order:
    pattern:  /payum/
    defaults: { _controller: AiselOrderBundle:Payum:order, _format: json }
    requirements:
        _method: GET
