api_aisel_configcontact:
    pattern:  /api/config/contact.json
    defaults: { _controller: AiselContactBundle:Api:config, _format: json }
    requirements:
        _method: GET

api_aisel_contactsend:
    pattern:  /api/contact/send.json
    defaults: { _controller: AiselContactBundle:Api:send, _format: json }
    requirements:
        _method: GET
