parameters:
    aisel_contact_manager.class: Aisel\ContactBundle\Manager\ContactManager

services:
    aisel.contact.manager:
        class: %aisel_contact_manager.class%
        arguments: [@doctrine.orm.entity_manager, @mailer, @templating,  %application.email% ]
