parameters:
#    aisel_contact.example.class: Aisel\ContactBundle\Example

services:
#    aisel_contact.example:
#        class: %aisel_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
