# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

admin_api_aisel_order_get_collection:
    pattern:   /order/
    defaults:  { _controller: AiselOrderBundle:Admin/Api:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_aisel_order_get:
    pattern:   /order/{id}
    defaults:  { _controller: AiselOrderBundle:Admin/Api:get, _format: json }
    requirements:
        _method: GET

admin_api_aisel_order_put:
    pattern:   /order/{id}
    defaults:  { _controller: AiselOrderBundle:Admin/Api:put, _format: json }
    requirements:
        _method: PUT

admin_api_aisel_order_delete:
    pattern:   /order/{id}
    defaults:  { _controller: AiselOrderBundle:Admin/Api:delete, _format: json }
    requirements:
        _method: DELETE

admin_api_aisel_order_post:
    pattern:   /order/
    defaults:  { _controller: AiselOrderBundle:Admin/Api:post, _format: json }
    requirements:
        _method: POST
