api_aisel_user_login:
    pattern:  /api/user/login.json
    defaults: { _controller: AiselUserBundle:Api:login, _format: json }
    requirements:
        _method: GET

api_aisel_user_logout:
    pattern:  /api/user/logout.json
    defaults: { _controller: AiselUserBundle:Api:logout, _format: json }
    requirements:
        _method: GET

api_aisel_user_information:
    pattern:  /api/user/information.json
    defaults: { _controller: AiselUserBundle:Api:information, _format: json }
    requirements:
        _method: GET

api_aisel_user_editdetails:
    pattern:  /api/user/editdetails.json
    defaults: { _controller: AiselUserBundle:Api:editdetails, _format: json }
    requirements:
        _method: GET

api_aisel_user_register:
    pattern:  /api/user/register.json
    defaults: { _controller: AiselUserBundle:Api:register, _format: json }
    requirements:
        _method: GET

api_aisel_user_passwordforgot:
    pattern:  /api/user/passwordforgot.json
    defaults: { _controller: AiselUserBundle:Api:passwordforgot, _format: json }
    requirements:
        _method: GET


#login:
#    pattern:   /login
#    defaults:  { _controller: AiselUserBundle:Security:login }
#login_check:
#    pattern:   /login_check
#logout:
#    pattern:   /logout
#
#test_security:
#    pattern: /secure_area
#    defaults: {_controller: AiselUserBundle:Security:dumpString }
