services:
    sonata.user.admin.group:
        abstract: true
        public: false


    sonata.admin.user.frontend:
        class: Aisel\UserBundle\Admin\FrontendUserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "System", label: "Frontend Users" }
        arguments:
            - ~
            - Aisel\UserBundle\Entity\FrontendUser
            - ~
        calls:
            - [ setTranslationDomain, [AiselUserBundle]]
            - [ setEncoderFactory, [ @security.encoder_factory ] ]

#    frontend.user.provider:
#        class: Doctrine\Common\Persistence\ObjectRepository
#        factory_service: doctrine
#        factory_method: getRepository
#        arguments: [ Aisel\UserBundle\Entity\FrontendUser ]

    frontend.user.manager:
        class: Aisel\UserBundle\Manager\UserManager
        arguments: [@doctrine.orm.entity_manager, @security.encoder_factory, @mailer, @templating, %application_email%, @security.context]
