parameters:
    aisel_adminconfig_manager.class: Aisel\AdminBundle\Manager\AdminConfigmanager

services:
    aisel.adminconfig.manager:
        class: %aisel_adminconfig_manager.class%
        arguments: [@doctrine.orm.entity_manager ]
