Aisel\NavigationBundle\Entity\Menu:
    type: entity
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    table: x_menu
    gedmo:
      tree:
        type: nested
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
      title:
        type: string
        length: 64
      lft:
        type: integer
        gedmo:
          - treeLeft
      rgt:
        type: integer
        gedmo:
          - treeRight
      root:
        type: integer
        nullable: true
        gedmo:
          - treeRoot
      lvl:
        type: integer
        gedmo:
          - treeLevel

      #GENERAL
      status:
          type: boolean
          column: status

      dateCreated:
          type: datetime
          column: date_created
      dateModified:
          type: datetime
          column: date_modified

    manyToOne:
      parent:
        targetEntity: Aisel\NavigationBundle\Entity\Menu
        inversedBy: children
        joinColumn:
          name: parent_id
          referencedColumnName: id
          onDelete: CASCADE
        gedmo:
          - treeParent

    oneToMany:
      children:
        targetEntity: Aisel\NavigationBundle\Entity\Menu
        mappedBy: parent
        orderBy:
          lft: ASC
