projectx_page_emptyhomepage:
    pattern:  /
    defaults: { _controller: ProjectxPageBundle:Default:index }

api_projectx_pagelist:
    pattern:  /api/page/list/
    defaults: { _controller: ProjectxPageBundle:Api:pageList, _format: json }
    requirements:
        _method: GET

api_projectx_pageview:
    pattern:  /api/page/view/{id}/
    defaults: { _controller: ProjectxPageBundle:Api:pageView, _format: json }
    requirements:
        _method: GET
        id: "\d+"
