#parameters:
#    aisel_category_manager.class: Aisel\CategoryBundle\Manager\CategoryManager
#    aisel_usercategory_manager.class: Aisel\CategoryBundle\Manager\UserCategoryManager
#
#services:
#    aisel.category.manager:
#        class: %aisel_category_manager.class%
#        arguments: [@service_container, @doctrine.orm.entity_manager]
#
#    aisel.usercategory.manager:
#        class: %aisel_category_manager.class%
#        arguments: [@service_container, @doctrine.orm.entity_manager, @security.context]