Aisel\CartBundle\Entity\Cart:
    type: entity
    table: aisel_cart
    repositoryClass: Aisel\CartBundle\Entity\CartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    manyToOne:
      frontenduser:
        targetEntity: Aisel\FrontendUserBundle\Entity\FrontendUser
        inversedBy: carts
        joinColumns:
          user_id:
            referencedColumnName: id