# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\CartBundle\Entity\Cart:
    type: entity
    table: aisel_cart
    repositoryClass: Aisel\CartBundle\Entity\CartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        qty:
            type: integer
            column: qty
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    manyToOne:
      frontenduser:
        targetEntity: Aisel\FrontendUserBundle\Entity\FrontendUser
        inversedBy: cart
        joinColumns:
          user_id:
            referencedColumnName: id

      product:
        targetEntity: Aisel\ProductBundle\Entity\Product
        inversedBy: cart
        joinColumn:
          name: product_id
          referencedColumnName: id