Aisel\AddressingBundle\Entity\Address:
    type: entity
    table: aisel_address
    repositoryClass: Aisel\AddressingBundle\Entity\AddressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        phone:
            type: string
            length: 255
            nullable: true
        street:
            type: string
            length: 255
            nullable: true
        zip:
            type: string
            length: 255
            nullable: true
        comment:
            type: text
            nullable: true

        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    #User
    manyToOne:
      frontenduser:
        targetEntity: Aisel\FrontendUserBundle\Entity\FrontendUser
        inversedBy: addresses
        joinColumns:
          user_id:
            referencedColumnName: id

    oneToOne:
      country:
        targetEntity: Aisel\AddressingBundle\Entity\Country
        joinColumn:
          name: county_id
          referencedColumnName: id

      region:
        targetEntity: Aisel\AddressingBundle\Entity\Region
        joinColumn:
          name: region_id
          referencedColumnName: id

      city:
        targetEntity: Aisel\AddressingBundle\Entity\City
        joinColumn:
          name: city_id
          referencedColumnName: id
