Aisel\AddressingBundle\Entity\Address:
    type: entity
    table: aisel_address
    repositoryClass: Aisel\AddressingBundle\Entity\AddressRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        address:
            type: string
            length: 255

        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at