Aisel\AddressingBundle\Entity\City:
    type: entity
    table: aisel_city
    repositoryClass: Aisel\AddressingBundle\Entity\CityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    oneToOne:
      country:
        targetEntity: Aisel\AddressingBundle\Entity\Country
        joinColumn:
          name: county_id
          referencedColumnName: id

      region:
        targetEntity: Aisel\AddressingBundle\Entity\Region
        joinColumn:
          name: region_id
          referencedColumnName: id
