Aisel\AddressingBundle\Entity\Region:
    type: entity
    table: aisel_region
    repositoryClass: Aisel\AddressingBundle\Entity\RegionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255


        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    oneToOne:
      country:
        targetEntity: Aisel\AddressingBundle\Entity\Country
        joinColumn:
          name: county_id
          referencedColumnName: id