Aisel\ProductBundle\Entity\Image:
    type: entity
    table: aisel_product_image
    repositoryClass: Aisel\ProductBundle\Entity\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        filename:
            type: string
            nullable: true
            column: filename

    manyToOne:
      product:
        targetEntity: Aisel\ProductBundle\Entity\Product
        inversedBy: images
        joinColumns:
          product_id:
            referencedColumnName: id