Aisel\ProductBundle\Entity\Product:
    type: entity
    table: aisel_product
    repositoryClass: Aisel\ProductBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        sku:
            type: string
            length: 255
        price:
            type: float
            column: price
        priceSpecial:
            type: float
            nullable: true
            column: price_special
        priceSpecialFrom:
            type: datetime
            nullable: true
            column: price_special_from
        priceSpecialTo:
            type: datetime
            nullable: true
            column: price_special_to

        new:
            type: boolean
            nullable: true
            column: is_new
        newFrom:
            type: datetime
            nullable: true
            column: new_from
        newTo:
            type: datetime
            nullable: true
            column: new_to

        inStock:
            type: boolean
            nullable: true
            column: in_stock


        descriptionShort:
            type: text
            column: description_short
        description:
            type: text
            column: description
        status:
            type: boolean
            column: status
        hidden:
            type: boolean
            column: is_hidden
        commentStatus:
            type: boolean
            nullable: true
            column: comment_status

        metaUrl:
            type: string
            unique: true
            length: 255
            column: meta_url
        metaTitle:
            type: string
            nullable: true
            length: 255
            column: meta_title
        metaDescription:
            nullable: true
            type: string
            length: 255
            column: meta_description
        metaKeywords:
            type: string
            nullable: true
            length: 255
            column: meta_keywords

        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    manyToOne:
      frontenduser:
        targetEntity: Aisel\FrontendUserBundle\Entity\FrontendUser
        inversedBy: products
        joinColumns:
          user_id:
            referencedColumnName: id

    oneToMany:
      image:
        targetEntity: Aisel\ProductBundle\Entity\Image
        mappedBy: product


    manyToMany:
      categories:
        targetEntity: Aisel\CategoryBundle\Entity\Category
        joinTable:
          name: aisel_product_category
          joinColumns:
            product_id:
              referencedColumnName: id
          inverseJoinColumns:
            category_id:
              referencedColumnName: id