# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\ProductBundle\Entity\Product:
  exclusion_policy: ALL
  properties:
    id:
        expose: true
    name:
        expose: true
    sku:
        expose: true
    price:
        expose: true
    descriptionShort:
        expose: true
    description:
        expose: true
    commentStatus:
        expose: true
    metaUrl:
        expose: true
    metaTitle:
        expose: true
    metaDescription:
        expose: true
    metaKeywords:
        expose: true
    status:
        expose: true

    createdAt:
        expose: true
    updatedAt:
        expose: true
