api_aisel_navigationmenu:
    pattern:  /api/navigation/menu.json
    defaults: { _controller: AiselNavigationBundle:Api:menu, _format: json }
    requirements:
        _method: GET

admin_aisel_navigation_menu_update:
    pattern:   /administration/navigation/menu/{id}/update.json
    defaults:  { _controller: AiselNavigationBundle:Admin:update, _format: json }
    requirements:
        _method: GET