# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Frontend
api_aisel_navigationmenu:
    pattern:  /%frontend_api%/{locale}/navigation/menu.json
    defaults: { _controller: AiselNavigationBundle:Api:menu, _format: json }
    requirements:
        _method: GET

# Backend
admin_aisel_navigation_menu_get:
    pattern:   /%backend_api%/navigation/tree/
    defaults:  { _controller: AiselNavigationBundle:Admin/Node:getTree, _format: json }
    requirements:
        _method: GET

admin_aisel_navigation_get:
    pattern:   /%backend_api%/navigation/{id}
    defaults:  { _controller: AiselNavigationBundle:Admin/Node:get, _format: json }
    requirements:
        _method: GET
