# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_navigationmenu:
    pattern:  /%website_api%/navigation/menu.json
    defaults: { _controller: AiselNavigationBundle:Api:menu, _format: json }
    requirements:
        _method: GET

admin_aisel_navigation_menu_update:
    pattern:   /%website_admin%/navigation/menu/update.json
    defaults:  { _controller: AiselNavigationBundle:Admin/Node:update, _format: json }
    requirements:
        _method: GET
