api_aisel_navigationmenu:
    pattern:  /api/navigation/menu.json
    defaults: { _controller: AiselNavigationBundle:Api:menu, _format: json }
    requirements:
        _method: GET

aisel_menu_tree_up:
    pattern:  /administration/aisel/navigation/menu/up/{id}
    defaults:  { _controller: AiselNavigationBundle:MenuSort:up }

aisel_menu_tree_down:
    pattern:  /administration/aisel/navigation/menu/down/{id}
    defaults:  { _controller: AiselNavigationBundle:MenuSort:down }
