aisel_menu_tree_up:
    pattern:  /administration/aisel/navigation/menu/up/{id}
    defaults:  { _controller: AiselNavigationBundle:AdminMenuNavigationSort:up }

aisel_menu_tree_down:
    pattern:  /administration/aisel/navigation/menu/down/{id}
    defaults:  { _controller: AiselNavigationBundle:AdminMenuNavigationSort:down }
