parameters:
    aisel_navigation_manager.class: Aisel\NavigationBundle\Manager\NavigationManager
    aisel_navigation_node_manager.class: Aisel\NavigationBundle\Manager\NodeManager

services:
    aisel.navigation.manager:
        class: %aisel_navigation_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]

    aisel.navigation.node.manager:
        class: %aisel_navigation_node_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]

    sonata.admin.navigation:
        class: Aisel\NavigationBundle\Admin\NavigationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Navigation", label: "Menu" }
        arguments:
            - ~
            - Aisel\NavigationBundle\Entity\Menu
            - ~
        calls:
            - [ setTranslationDomain, [AiselNavigationBundle]]
            - [ setTemplate, [list, AiselNavigationBundle:Tree:list.html.twig]]