parameters:
    aisel_addressing_manager.class: Aisel\AddressingBundle\Manager\AddressingManager

services:
    aisel.addressing.manager:
        class: %aisel_addressing_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]