# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    aisel_config_manager.class: Aisel\ConfigBundle\Manager\ConfigManager
    aisel_routing_loader.class: Aisel\ConfigBundle\Routing\ExtraLoader

services:
    aisel_config.routing_loader:
        class: %aisel_routing_loader.class%
        tags:
            - { name: routing.loader }
        arguments: [@service_container]

    aisel.config.manager:
        class: %aisel_config_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - "%locale%"
            - "%locales%"