# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    aisel_config.routing_loader:
        class: Aisel\ConfigBundle\Routing\ExtraLoader
        tags:
            - { name: routing.loader }
        arguments: [@service_container]
