# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_media_upload:
    path:   /media/upload/{type}/
    defaults:  { _controller: AiselMediaBundle:Upload:upload, _format: json }
    requirements:
        _method: GET|POST

admin_api_aisel_media_post:
    path:   /media/
    defaults:  { _controller: AiselMediaBundle:Admin/ApiMedia:post, _format: json }
    requirements:
        _method: POST

admin_api_aisel_media_get:
    path:   /media/{id}
    defaults:  { _controller: AiselMediaBundle:Admin/ApiMedia:get, _format: json }
    requirements:
        _method: GET

admin_api_aisel_media_put:
    path:   /media/{id}
    defaults:  { _controller: AiselMediaBundle:Admin/ApiMedia:put, _format: json }
    requirements:
        _method: PUT

admin_api_aisel_media_delete:
    path:   /media/{id}
    defaults:  { _controller: AiselMediaBundle:Admin/ApiMedia:delete, _format: json }
    requirements:
        _method: DELETE
