# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Aisel\PageBundle\Entity\Page:
    type: entity
    table: aisel_page
    repositoryClass: Aisel\PageBundle\Entity\PageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 2
            nullable: false

        title:
            type: string
            length: 255
        content:
            type: text
        status:
            type: boolean
            column: status
        hidden:
            type: boolean
            column: is_hidden
        commentStatus:
            type: boolean
            nullable: true
            column: comment_status

        metaUrl:
            type: string
            unique: true
            length: 255
            column: meta_url
        metaTitle:
            type: string
            nullable: true
            length: 255
            column: meta_title
        metaDescription:
            nullable: true
            type: string
            length: 255
            column: meta_description
        metaKeywords:
            type: string
            nullable: true
            length: 255
            column: meta_keywords

        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    manyToOne:
      frontenduser:
        targetEntity: Aisel\FrontendUserBundle\Entity\FrontendUser
        inversedBy: pages
        joinColumns:
          user_id:
            referencedColumnName: id

    manyToMany:
      categories:
        targetEntity: Aisel\PageBundle\Entity\Category
        joinTable:
          name: aisel_page_page_category
          joinColumns:
            page_id:
              referencedColumnName: id
          inverseJoinColumns:
            category_id:
              referencedColumnName: id

#    lifecycleCallbacks: {  }
#    lifecycleCallbacks:
#      prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
#      postPersist: [ doStuffOnPostPersist ]
