Aisel\PageBundle\Entity\Page:
    type: entity
    table: aisel_page
    repositoryClass: Aisel\PageBundle\Entity\PageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
#        user_id:
#            type: integer
#            nullable: true
        title:
            type: string
            length: 255
        content:
            type: text
        status:
            type: boolean
            column: status
        isHidden:
            type: boolean
            column: is_hidden
        commentStatus:
            type: boolean
            nullable: true
            column: comment_status
        metaUrl:
            type: string
            unique: true
            length: 255
            column: meta_url
        metaTitle:
            type: string
            nullable: true
            length: 255
            column: meta_title
        metaDescription:
            nullable: true
            type: string
            length: 255
            column: meta_description
        metaKeywords:
            type: string
            nullable: true
            length: 255
            column: meta_keywords

        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    manyToOne:
      frontenduser:
        targetEntity: Aisel\UserBundle\Entity\FrontendUser
        inversedBy: pages
        joinColumns:
          user_id:
            referencedColumnName: id

    manyToMany:
      categories:
        targetEntity: Aisel\CategoryBundle\Entity\Category
        joinTable:
          name: aisel_page_category
          joinColumns:
            page_id:
              referencedColumnName: id
          inverseJoinColumns:
            category_id:
              referencedColumnName: id
#    lifecycleCallbacks: {  }
#    lifecycleCallbacks:
#      prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
#      postPersist: [ doStuffOnPostPersist ]