Aisel\PageBundle\Entity\Page:
    type: entity
    table: x_page
    repositoryClass: Aisel\PageBundle\Entity\PageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        pageStatus:
            type:
            length: 25
            column: page_status
        commentStatus:
            type: boolean
            column: comment_status
        metaUrl:
            type: string
            length: 255
            column: meta_url
        metaTitle:
            type: string
            length: 255
            column: meta_title
        metaDescription:
            type: string
            length: 255
            column: meta_description
        metaKeywords:
            type: string
            length: 255
            column: meta_keywords
        dateCreated:
            type: datetime
            column: date_created
        dateModified:
            type: datetime
            column: date_modified
    manyToMany:
      categories:
        targetEntity: Aisel\CategoryBundle\Entity\Category
        joinTable:
          name: x_page_category
          joinColumns:
            page_id:
              referencedColumnName: id
          inverseJoinColumns:
            category_id:
              referencedColumnName: id
#    lifecycleCallbacks: {  }
#    lifecycleCallbacks:
#      prePersist: [ doStuffOnPrePersist, doOtherStuffOnPrePersistToo ]
#      postPersist: [ doStuffOnPostPersist ]