# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

api_aisel_settings:
    pattern:  /%website_api%/{locale}/config/settings.json
    defaults: { _controller: AiselSettingsBundle:ApiSettings:config, _format: json }
    requirements:
        _method: GET
