# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    aisel_settings_manager.class: Aisel\SettingsBundle\Manager\SettingsManager

services:
    aisel.settings.manager:
        class: %aisel_settings_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - "%locale%"
            - "%locales%"
