security:
    encoders:
        Aisel\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user:
            entity: { class: Aisel\UserBundle\Entity\User, property: username }

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
            pattern:             .*
            context:             user
            anonymous:           true

    access_control:
        - { path: ^/%backend_api%/user/login/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%backend_api%/user/information/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%backend_api%/user/logout/, role: IS_AUTHENTICATED_FULLY }

        - { path: ^/%backend_api%/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/%seller_api%/, role: IS_AUTHENTICATED_FULLY }
