Aisel\PageBundle\Entity\Page:
  exclusion_policy: ALL
  properties:
    id:
        expose: true
    title:
        expose: true
    content:
        expose: true
    createdAt:
        expose: true
    updatedAt:
        expose: true
    comment_status:
        expose: true
    metaUrl:
        expose: true
    metaTitle:
        expose: true
    metaDescription:
        expose: true
    metaKeywords:
        expose: true