api_aisel_pagelist:
    pattern:  /api/page/list.json
    defaults: { _controller: AiselPageBundle:Api:pageList, _format: json }
    requirements:
        _method: GET

api_aisel_pageview:
    pattern:  /api/page/view/{urlKey}.json
    defaults: { _controller: AiselPageBundle:Api:pageView, _format: json }
    requirements:
        _method: GET
        id: "\d+"

api_aisel_search:
    pattern:  /api/search/
    defaults: { _controller: AiselPageBundle:Api:search, _format: json }
    requirements:
        _method: GET
        id: "\d+"
