api_aisel_pagelist:
    pattern:  /api/page/list.json
    defaults: { _controller: AiselPageBundle:Api:pageList, _format: json }
    requirements:
        _method: GET

#api_aisel_pageview:
#    pattern:  /api/page/view/{urlKey}.json
#    defaults: { _controller: AiselPageBundle:Api:pageView, _format: json }
#    requirements:
#        _method: GET
#        id: "\d+"

api_aisel_pageview_by_url:
    pattern:  /api/page/view/url/{urlKey}.json
    defaults: { _controller: AiselPageBundle:Api:pageViewByURL, _format: json }
    requirements:
        _method: GET
#        id: "\d+"

api_aisel_search:
    pattern:  /api/search/
    defaults: { _controller: AiselPageBundle:Api:search, _format: json }
    requirements:
        _method: GET
#        id: "\d+"


# User specific actions


api_aisel_user_pagedetails_by_id:
    pattern:  /api/user/page/details/id/{pageId}.json
    defaults: { _controller: AiselPageBundle:ApiUserCRUD:pageDetails, _format: json }
    requirements:
        _method: GET
#        id: "\d+"

api_aisel_user_page_edit:
    pattern:  /api/user/page/edit/{pageId}.json
    defaults: { _controller: AiselPageBundle:ApiUserCRUD:pageEdit, _format: json }
#    requirements:
#        _method: POST

api_aisel_user_page_add:
    pattern:  /api/user/page/add.json
    defaults: { _controller: AiselPageBundle:ApiUserCRUD:pageAdd, _format: json }
#    requirements:
#        _method: POST

api_aisel_user_page_delete:
    pattern:  /api/user/page/delete/{pageId}.json
    defaults: { _controller: AiselPageBundle:ApiUserCRUD:pageDelete, _format: json }
#    requirements:
#        _method: POST
