api_aisel_pagelist:
    pattern:  /api/page/list.json
    defaults: { _controller: AiselPageBundle:Api:pageList, _format: json }
    requirements:
        _method: GET

api_aisel_pageview:
    pattern:  /api/page/view/{urlKey}.json
    defaults: { _controller: AiselPageBundle:Api:pageView, _format: json }
    requirements:
        _method: GET
        id: "\d+"

api_aisel_search:
    pattern:  /api/search/
    defaults: { _controller: AiselPageBundle:Api:search, _format: json }
    requirements:
        _method: GET
        id: "\d+"


# User specific actions

api_aisel_user_page_edit:
    pattern:  /api/user/page/edit/{id}.json
    defaults: { _controller: AiselPageBundle:ApiUser:pageEdit, _format: json }
    requirements:
        _method: GET
