# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Backend
admin_api_aisel_page_category_update:
    pattern:   /%website_admin%/page/category/update.json
    defaults:  { _controller: AiselPageBundle:Admin/Node:update, _format: json }
    requirements:
        _method: GET

admin_api_aisel_page_get_collection:
    pattern:   /%backend_api%/page/
    defaults:  { _controller: AiselPageBundle:Admin/Api:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_aisel_page_get:
    pattern:   /%backend_api%/page/{id}
    defaults:  { _controller: AiselPageBundle:Admin/Api:get, _format: json }
    requirements:
        _method: GET


# Frontend
api_aisel_pagelist:
    pattern:  /%frontend_api%/{locale}/page/list.json
    defaults: { _controller: AiselPageBundle:ApiPage:pageList, _format: json }
    requirements:
        _method: GET

api_aisel_pageview_by_url:
    pattern:  /%frontend_api%/{locale}/page/view/url/{urlKey}.json
    defaults: { _controller: AiselPageBundle:ApiPage:pageViewByURL, _format: json }
    requirements:
        _method: GET

api_aisel_page_categorylist:
    pattern:  /%frontend_api%/{locale}/page/category/list.json
    defaults: { _controller: AiselPageBundle:ApiCategory:categoryList, _format: json }
    requirements:
        _method: GET

api_aisel_page_categorytree:
    pattern:  /%frontend_api%/{locale}/page/category/tree.json
    defaults: { _controller: AiselPageBundle:ApiCategory:categoryTree, _format: json }
    requirements:
        _method: GET

api_aisel_page_categoryview:
    pattern:  /%frontend_api%/{locale}/page/category/view/{urlKey}.json
    defaults: { _controller: AiselPageBundle:ApiCategory:categoryView, _format: json }
    requirements:
        _method: GET
        id: "\d+"
