# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Administration
admin_aisel_page_category_update:
    pattern:   /%website_admin%/page/category/update.json
    defaults:  { _controller: AiselPageBundle:Admin/Node:update, _format: json }
    requirements:
        _method: GET
# Api
# Product
api_aisel_pagelist:
    pattern:  /%website_api%/page/list.json
    defaults: { _controller: AiselPageBundle:ApiPage:pageList, _format: json }
    requirements:
        _method: GET

api_aisel_pageview_by_url:
    pattern:  /%website_api%/page/view/url/{urlKey}.json
    defaults: { _controller: AiselPageBundle:ApiPage:pageViewByURL, _format: json }
    requirements:
        _method: GET

# Categories
api_aisel_page_categorylist:
    pattern:  /%website_api%/page/category/list.json
    defaults: { _controller: AiselPageBundle:ApiCategory:categoryList, _format: json }
    requirements:
        _method: GET

api_aisel_page_categorytree:
    pattern:  /%website_api%/page/category/tree.json
    defaults: { _controller: AiselPageBundle:ApiCategory:categoryTree, _format: json }
    requirements:
        _method: GET

api_aisel_page_categoryview:
    pattern:  /%website_api%/page/category/view/{urlKey}.json
    defaults: { _controller: AiselPageBundle:ApiCategory:categoryView, _format: json }
    requirements:
        _method: GET
        id: "\d+"

# User specific actions
api_aisel_user_pagedetails_by_id:
    pattern:  /%website_api%/user/page/details/id/{pageId}.json
    defaults: { _controller: AiselPageBundle:ApiUserPage:pageDetails, _format: json }
    requirements:
        _method: GET

api_aisel_user_page_edit:
    pattern:  /%website_api%/user/page/edit/{pageId}.json
    defaults: { _controller: AiselPageBundle:ApiUserPage:pageEdit, _format: json }
    requirements:
        _method: GET

api_aisel_user_page_add:
    pattern:  /%website_api%/user/page/add.json
    defaults: { _controller: AiselPageBundle:ApiUserPage:pageAdd, _format: json }
    requirements:
        _method: GET

api_aisel_user_page_delete:
    pattern:  /%website_api%/user/page/delete/{pageId}.json
    defaults: { _controller: AiselPageBundle:ApiUserPage:pageDelete, _format: json }
    requirements:
        _method: GET

api_aisel_user_categorytree:
    pattern:  /%website_api%/user/category/tree.json
    defaults: { _controller: AiselPageBundle:ApiUserCategory:categoryTree, _format: json }
    requirements:
        _method: GET
