api_aisel_pagelist:
    pattern:  /api/page/list.json
    defaults: { _controller: AiselPageBundle:ApiPage:pageList, _format: json }
    requirements:
        _method: GET

api_aisel_pageview_by_url:
    pattern:  /api/page/view/url/{urlKey}.json
    defaults: { _controller: AiselPageBundle:ApiPage:pageViewByURL, _format: json }
    requirements:
        _method: GET


#Categories
api_aisel_page_categorylist:
    pattern:  /api/page/category/list.json
    defaults: { _controller: AiselPageBundle:ApiCategory:categoryList, _format: json }
    requirements:
        _method: GET

api_aisel_page_categorytree:
    pattern:  /api/page/category/tree.json
    defaults: { _controller: AiselPageBundle:ApiCategory:categoryTree, _format: json }
    requirements:
        _method: GET

api_aisel_page_categoryview:
    pattern:  /api/page/category/view/{urlKey}.json
    defaults: { _controller: AiselPageBundle:ApiCategory:categoryView, _format: json }
    requirements:
        _method: GET
        id: "\d+"

# User specific actions

# User specific actions
api_aisel_user_pagedetails_by_id:
    pattern:  /api/user/page/details/id/{pageId}.json
    defaults: { _controller: AiselPageBundle:ApiUserPage:pageDetails, _format: json }
    requirements:
        _method: GET

api_aisel_user_page_edit:
    pattern:  /api/user/page/edit/{pageId}.json
    defaults: { _controller: AiselPageBundle:ApiUserPage:pageEdit, _format: json }
    requirements:
        _method: GET

api_aisel_user_page_add:
    pattern:  /api/user/page/add.json
    defaults: { _controller: AiselPageBundle:ApiUserPage:pageAdd, _format: json }
    requirements:
        _method: GET

api_aisel_user_page_delete:
    pattern:  /api/user/page/delete/{pageId}.json
    defaults: { _controller: AiselPageBundle:ApiUserPage:pageDelete, _format: json }
    requirements:
        _method: GET

api_aisel_user_categorytree:
    pattern:  /api/user/category/tree.json
    defaults: { _controller: AiselPageBundle:ApiUserCategory:categoryTree, _format: json }
    requirements:
        _method: GET
