# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    aisel_page_category_mode_manager.class: Aisel\PageBundle\Manager\NodeManager
    aisel_page_url_persistence_listener.class: Aisel\PageBundle\EventListener\PageUrlPersistenceListener
    aisel_page_category_url_persistence_listener.class: Aisel\PageBundle\EventListener\CategoryUrlPersistenceListener

services:
    aisel.pagecategory.node.manager:
        class: %aisel_page_category_mode_manager.class%
        arguments:
          - @doctrine.odm.mongodb.document_manager
          - "%locales%"

    aisel_page_url_persistence_listener:
        class: %aisel_page_url_persistence_listener.class%
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }

    aisel_page_category_url_persistence_listener:
        class: %aisel_page_category_url_persistence_listener.class%
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
