# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    aisel_page_category_mode_manager.class: Aisel\PageBundle\Manager\NodeManager

services:
    aisel.pagecategory.node.manager:
        class: %aisel_page_category_mode_manager.class%
        arguments:
          - @doctrine.orm.entity_manager
          - "%locales%"
