# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    aisel_page_manager.class: Aisel\PageBundle\Manager\PageManager
    aisel_page_category_manager.class: Aisel\PageBundle\Manager\CategoryManager
    aisel_page_category_mode_manager.class: Aisel\PageBundle\Manager\NodeManager

services:
    aisel.page.manager:
        class: %aisel_page_manager.class%
        arguments:
            - @doctrine.orm.entity_manager

    aisel.pagecategory.manager:
        class: %aisel_page_category_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]

    aisel.pagecategory.node.manager:
        class: %aisel_page_category_mode_manager.class%
        arguments:
          - @doctrine.orm.entity_manager
