parameters:
    aisel_page_manager.class: Aisel\PageBundle\Manager\PageManager
    aisel_userpage_manager.class: Aisel\PageBundle\Manager\UserPageManager

services:
    sonata.admin.page:
        class: Aisel\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Pages" }
        arguments:
            - ~
            - Aisel\PageBundle\Entity\Page
            - ~
        calls:
            - [ setTranslationDomain, [AiselPageBundle]]
            - [ setManager, [@aisel.page.manager]]
    aisel.page.manager:
        class: %aisel_page_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]

    aisel.userpage.manager:
        class: %aisel_userpage_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager, @security.context, @aisel.page.manager]
