parameters:
    aisel_page_manager.class: Aisel\PageBundle\Manager\PageManager
    aisel_page_category_manager.class: Aisel\PageBundle\Manager\CategoryManager
    aisel_userpage_manager.class: Aisel\PageBundle\Manager\UserPageManager
    aisel_usercategory_manager.class: Aisel\PageBundle\Manager\UserCategoryManager


services:
    aisel.page.manager:
        class: %aisel_page_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]

    aisel.pagecategory.manager:
        class: %aisel_page_category_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]

    aisel.userpage.manager:
        class: %aisel_userpage_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager, @security.context, @aisel.page.manager]

    aisel.usercategory.manager:
        class: %aisel_usercategory_manager.class%
        arguments: [@service_container, @doctrine.orm.entity_manager, @security.context, @aisel.page.manager]


    sonata.admin.page:
        class: Aisel\PageBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Pages" }
        arguments:
            - ~
            - Aisel\PageBundle\Entity\Page
            - ~
        calls:
            - [ setTranslationDomain, [AiselPageBundle]]
            - [ setManager, [@aisel.page.manager]]

    sonata.admin.page.category:
        class: Aisel\PageBundle\Admin\PageCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Categories" }
        arguments:
            - ~
            - Aisel\PageBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [AiselPageBundle]]
            - [ setTemplate, [list, AiselPageBundle:Tree:list.html.twig]]
            - [ setManager, [@aisel.pagecategory.manager]]
