# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

#Product Node
admin_api_aisel_product_node_get:
    pattern:   /product/node/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:get, _format: json }
    requirements:
        _method: GET

admin_api_aisel_product_node_get_collectiom:
    pattern:   /product/node/
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_aisel_product_node_get_tree:
    pattern:   /product/node/tree/
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:getTree, _format: json }
    requirements:
        _method: GET

admin_api_aisel_product_node_put:
    pattern:   /product/node/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:put, _format: json }
    requirements:
        _method: PUT

admin_api_aisel_product_node_post:
    pattern:   /product/node/
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:post, _format: json }
    requirements:
        _method: POST

admin_api_aisel_product_node_delete:
    pattern:   /product/node/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiNode:delete, _format: json }
    requirements:
        _method: DELETE

#Product
admin_api_aisel_product_get:
    pattern:   /product/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiProduct:get, _format: json }
    requirements:
        _method: GET

admin_api_aisel_product_delete:
    pattern:   /product/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiProduct:delete, _format: json }
    requirements:
        _method: DELETE

admin_api_aisel_product_put:
    pattern:   /product/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiProduct:put, _format: json }
    requirements:
        _method: PUT

admin_api_aisel_product_get_collection:
    pattern:   /product/
    defaults:  { _controller: AiselProductBundle:Admin/ApiProduct:getCollection, _format: json }
    requirements:
        _method: GET

# Reviews
admin_api_aisel_product_review_get:
    pattern:   /product/review/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiReview:get, _format: json }
    requirements:
        _method: GET

admin_api_aisel_product_review_get_collection:
    pattern:   /product/review/
    defaults:  { _controller: AiselProductBundle:Admin/ApiReview:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_aisel_product_review_put:
    pattern:   /product/review/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiReview:put, _format: json }
    requirements:
        _method: PUT

admin_api_aisel_product_review_delete:
    pattern:   /product/review/{id}
    defaults:  { _controller: AiselProductBundle:Admin/ApiReview:delete, _format: json }
    requirements:
        _method: DELETE