# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Backend
admin_api_aisel_frontenduser_get_collection:
    pattern:   /%backend_api%/frontenduser/
    defaults:  { _controller: AiselFrontendUserBundle:Admin/Api:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_aisel_frontenduser_get:
    pattern:   /%backend_api%/frontenduser/{id}
    defaults:  { _controller: AiselFrontendUserBundle:Admin/Api:get, _format: json }
    requirements:
        _method: GET

# Frontend
api_aisel_user_login:
    pattern:  /%frontend_api%/user/login.json
    defaults: { _controller: AiselFrontendUserBundle:Api:login, _format: json }
    requirements:
        _method: GET

api_aisel_user_logout:
    pattern:  /%frontend_api%/user/logout.json
    defaults: { _controller: AiselFrontendUserBundle:Api:logout, _format: json }
    requirements:
        _method: GET

api_aisel_user_information:
    pattern:  /%frontend_api%/user/information.json
    defaults: { _controller: AiselFrontendUserBundle:Api:information, _format: json }
    requirements:
        _method: GET

api_aisel_user_editdetails:
    pattern:  /%frontend_api%/user/editdetails.json
    defaults: { _controller: AiselFrontendUserBundle:Api:editdetails, _format: json }
    requirements:
        _method: GET

api_aisel_user_register:
    pattern:  /%frontend_api%/user/register.json
    defaults: { _controller: AiselFrontendUserBundle:Api:register, _format: json }
    requirements:
        _method: GET

api_aisel_user_passwordforgot:
    pattern:  /%frontend_api%/user/passwordforgot.json
    defaults: { _controller: AiselFrontendUserBundle:Api:passwordforgot, _format: json }
    requirements:
        _method: GET
