# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    aisel.user.frontend:
        class: Aisel\FrontendUserBundle\Admin\FrontendUserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Frontend" }
        arguments:
            - ~
            - Aisel\FrontendUserBundle\Entity\FrontendUser
            - ~
        calls:
            - [ setTranslationDomain, [forms]]
            - [ setEncoderFactory, [ @security.encoder_factory ] ]

    frontend.user.manager:
        class: Aisel\FrontendUserBundle\Manager\UserManager
        arguments:
          - @doctrine.orm.entity_manager
          - @security.encoder_factory
          - @mailer
          - @templating
          - %website_email%
          - @security.context
