# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    frontend.user.manager:
        class: Aisel\FrontendUserBundle\Manager\UserManager
        arguments:
          - @doctrine.orm.entity_manager
          - @security.encoder_factory
          - @security.context
          - @frontend.user_mail.manager

    frontend.user_mail.manager:
        class: Aisel\FrontendUserBundle\Manager\UserMailManager
        arguments:
          - @mailer
          - @templating
          - %website_email%

    aisel_frontend_user_persistence_listener:
        class: Aisel\FrontendUserBundle\EventListener\UserPersistenceListener
        arguments:
            - @security.encoder_factory
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
