api_aisel_productlist:
    pattern:  /api/product/list.json
    defaults: { _controller: AiselProductBundle:Api:productList, _format: json }
    requirements:
        _method: GET

api_aisel_productview_by_url:
    pattern:  /api/product/view/url/{urlKey}.json
    defaults: { _controller: AiselProductBundle:Api:productViewByURL, _format: json }
    requirements:
        _method: GET
#        id: "\d+"
