# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Backend
admin_aisel_product_media_upload:
    pattern:  /%website_admin%/product/media/{productId}/
    defaults: { _controller: AiselProductBundle:Admin/Media:upload, productId: 0 }
    requirements:
        _method:  OPTIONS|HEAD|GET|POST|PUT|PATCH|DELETE
        productId: "\d+"

admin_aisel_product_category_update:
    pattern:   /%website_admin%/product/category/update.json
    defaults:  { _controller: AiselProductBundle:Admin/Node:update, _format: json }
    requirements:
        _method: GET

admin_api_aisel_product_get_collection:
    pattern:   /%backend_api%/product/
    defaults:  { _controller: AiselProductBundle:Admin/Api:getCollection, _format: json }
    requirements:
        _method: GET

admin_api_aisel_product_get:
    pattern:   /%backend_api%/product/{id}
    defaults:  { _controller: AiselProductBundle:Admin/Api:get, _format: json }
    requirements:
        _method: GET

# Frontend
api_aisel_productlist:
    pattern:  /%frontend_api%/{locale}/product/list.json
    defaults: { _controller: AiselProductBundle:ApiProduct:productList, _format: json }
    requirements:
        _method: GET|POST

api_aisel_productview_by_url:
    pattern:  /%frontend_api%/{locale}/product/view/url/{urlKey}.json
    defaults: { _controller: AiselProductBundle:ApiProduct:productViewByURL, _format: json }
    requirements:
        _method: GET|POST

# Categories
api_aisel_product_categorylist:
    pattern:  /%frontend_api%/{locale}/product/category/list.json
    defaults: { _controller: AiselProductBundle:ApiCategory:categoryList, _format: json }
    requirements:
        _method: GET

api_aisel_product_categorytree:
    pattern:  /%frontend_api%/{locale}/product/category/tree.json
    defaults: { _controller: AiselProductBundle:ApiCategory:categoryTree, _format: json }
    requirements:
        _method: GET

api_aisel_product_categoryview:
    pattern:  /%frontend_api%/{locale}/product/category/view/{urlKey}.json
    defaults: { _controller: AiselProductBundle:ApiCategory:categoryView, _format: json }
    requirements:
        _method: GET
        id: "\d+"
