api_aisel_productlist:
    pattern:  /api/product/list.json
    defaults: { _controller: AiselProductBundle:Api:productList, _format: json }
    requirements:
        _method: GET|POST

api_aisel_productview_by_url:
    pattern:  /api/product/view/url/{urlKey}.json
    defaults: { _controller: AiselProductBundle:Api:productViewByURL, _format: json }
    requirements:
        _method: GET|POST

admin_aisel_product_media_upload:
    pattern:  /%website_admin%/product/media/{productId}/
    defaults: { _controller: AiselProductBundle:Media:upload, productId: 0 }
    requirements:
        _method:  OPTIONS|HEAD|GET|POST|PUT|PATCH|DELETE
        productId: "\d+"