# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    aisel_product_media_manager.class: Aisel\ProductBundle\Manager\MediaManager
    aisel_product_node_manager.class: Aisel\ProductBundle\Manager\NodeManager
    aisel_product_url_persistence_listener.class: Aisel\ProductBundle\EventListener\ProductUrlPersistenceListener

services:
    aisel.product.media.manager:
        class: %aisel_product_media_manager.class%
        arguments: [@doctrine.orm.entity_manager, %application.media.product.path%, %website_address%]

    aisel.productcategory.node.manager:
        class: %aisel_product_node_manager.class%
        arguments:
          - @doctrine.orm.entity_manager
          - "%locales%"

    aisel_product_url_persistence_listener:
        class: %aisel_product_url_persistence_listener.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }