# This file is part of the Aisel package.
#
# (c) Ivan Proskuryakov
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    aisel_product_media_manager.class: Aisel\ProductBundle\Manager\MediaManager
    aisel_product_node_manager.class: Aisel\ProductBundle\Manager\NodeManager

services:
    aisel.product.media.manager:
        class: %aisel_product_media_manager.class%
        arguments: [@doctrine.orm.entity_manager, %application.media.product.path%, %website_address%]

    aisel.productcategory.node.manager:
        class: %aisel_product_node_manager.class%
        arguments:
          - @doctrine.orm.entity_manager
          - "%locales%"
